# SPDX-FileCopyrightText: Michael Weimann <mail@michael-weimann.eu>
#
# SPDX-License-Identifier: MIT

version: 9
jobs:
- name: GitHub sync
  steps:
  - !CheckoutStep
    name: checkout
    cloneCredential: !DefaultCredential {}
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Push to GitHub
    image: alpine/git:1.0.32
    commands:
    - git config --global --unset http.extraHeader
    - git push --force https://weeman1337:@secrets:github-token@@@github.com/weeman1337/telescope-live-grep-raw.nvim HEAD:main
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: main
    projects: telescope-live-grep-raw.nvim
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250m
  memoryRequirement: 128m
  timeout: 3600
